### ISSUE TITLE
bigger view of a graph ends up below previews

### ISSUE THREAD

**Issue by klaernie** [chteuchteu/Munin-for-Android-Chromecast-Receiver#1]
The bigger display of a single graph is overflown by the previews.
![img_20150321_180551](https://cloud.githubusercontent.com/assets/5636383/6766018/c39ab8ce-cff5-11e4-8693-8a7b0f327f79.jpg)

**Comment by quentin-st** [comment]
This issue has actually been fixed in the [last commit](https://github.com/chteuchteu/Munin-for-Android-Chromecast-Receiver/commit/d6f387389c3d86c7689541900d4d7610ea704546), but changes hadn't been published on the server... Shame on me!
