### ISSUE TITLE
3x3 grid gets cut of

### ISSUE THREAD

**Issue by klaernie** [chteuchteu/Munin-for-Android-Chromecast-Receiver#4]
While there would be enough space to physically fit a 9x9 grid onto the big screen the bottom-most row gets cut off.

I think the top header-line throws of the calculation, and I wouldn't even display it in the first place. As soon as the application has loaded on the Chromecast its all about the contents, the name of the application is irrelevant at this time. Also the grids name doesn't meet to be spelled out, as the user always can see this in the android app. So once the header is out of the way the calculation should be much easier.

**Comment by quentin-st** [comment]
Fitting an entire grid was quite difficult so I dropped this and made all the calculation on the grid width. For now, indeed, only the first lines will be displayed on the screen.

I'm afraid that if there are too many items in the grid, grid items won't be readable anymore... But that's still better than only seeing half of them!

Adding it to the todo-list!

**Comment by klaernie** [comment]
Oops - it was a 3x3 grid, so actually readable at FullHD..

**Comment by klaernie** [comment]
@chteuchteu what do you think about removing the header line ? I think this should make any grid fit, as long as it is a 1:1 ratio (the graph previews have about a 16:9 ratio, so it would devide evenly)

**Comment by quentin-st** [comment]
Removing the header line would indeed free some space but someone who would look at the TV screen wouldn't see at first glance what it is about... Plus, we would lose the grid name.
Actually, we could put the app icon and the grid name in one of the two upper corners in order to free some space and reduce the header height!

I'm currently displaying a 3:3 grid on my TV screen right now, and even by removing the header, the third line wouldn't be displayed entirely...

I don't think that we could reduce the grid item height (all the remaining information is important (plugin name, server and master names) ; please note that I had to cut the graphs legends in order to free some space.

I think that trying to display the whole grid is the right solution. The big con is that graphs will be really small with a huge amount of grid items, but they would still be shown.

**Comment by klaernie** [comment]
Well, I think the grid name could definitely go into the border or overlayed, so it doesn't take up real estate, but overshadows a bit.

Also the type/names could be all a similar small size, I e.g. won't need the plugin type, as I group similar plugins in to a grid. Could one make that configurable?

I also like that the legends are missing, consider the use case in a small company, where a TV with Chromecast shows the stats of the most critical infrastructure, where everybody knows what each graph is, even without any label at all.

Also I think it would be alright to slim the borders on demand, e.g. if it doesn't fit nicely by default reduce the borders until it does.

**Comment by quentin-st** [comment]
Do you think that a "Hide grid items legend" option would fit your needs? That would indeed free a lot of space in your use case!

Actually, grid items width is dynamic (soon, it will be width & height): it is reduced until there is enough space to display all the grid items.

I'm currently working on HD graphs on preview, but as soon as I'll work on scaling the grid to display all grid items, I'll try to reduce paddings & margins!

**Comment by klaernie** [comment]
I'd say make every item configurable. It should be an option on the grid itself, to choose, if the plugin name, the group or the hostname are shown. Also some global tristate options should be there, to make it hide always, hide never or hide of the information is superfluous (all graphs in the grid are from the same host).

**Comment by quentin-st** [comment]
I'd rather put this in the Settings screen since there's no configuration on each grid. Plus, one would have to set it for each grid...
What about this?

> Plugin name: Show/Hide
> Server name: Show/Show when necessary/Hide
> Master name: Show/Show when necessary/Hide

**Comment by klaernie** [comment]
Well, what if you have one grid for the application-stack (webserver, db, is, network), and another for the big cluster, where you just have one plugin type, but hostnames are relevant?

I think it should be configurable globally, and optionally overwritable for each grid.

Also the plugin name should be able to hide automatically (e.g. the second grid above)

**Comment by quentin-st** [comment]
I see the point, but that would complicate the app a lot, don't you think? Plus, grids screens are quite full yet... 
Actually, the plugin name is already displayed on the graph (on top of it), so in this case it would be possible to completely hide the plugin name in the settings!

Yes, so each item (plugin name, server name, master name) would have a "Show when necessary" option!

**Comment by klaernie** [comment]
Well, I think we can keep this corner case in the back pocket, and rethink it I'd there are people who actually use this heavily and are annoyed if they can't configure it separately.

**Comment by quentin-st** [comment]
Yes indeed! BTW, I changed the "Support" menu item name to "Support / feedback" so users won't think this is only for support. Then, I'll wait and see if some other users are requesting this.

Thank you for the opened issues and the ideas!

**Comment by quentin-st** [comment]
This issue was solved by b9bd0a7 & 9be129c
