### ISSUE TITLE
receiver should update graphs on it's own

### ISSUE THREAD

**Issue by klaernie** [chteuchteu/Munin-for-Android-Chromecast-Receiver#6]
As the receiver is now able to run for hours straight it should also refresh the graphs on its own.

It should refresh the graph regularly every 5 minutes in general, but learn the servers processing time during the first couple runs (e.g. run the first 6 times every 60 seconds, and one the graphs are updated the first time start the regular 5 minutes interval).

**Comment by quentin-st** [comment]
The graphs are already refreshed when they are (manually or automatically) refreshed on the device, but we could indeed mix both!

**Comment by klaernie** [comment]
Works awesome!
